version: "3.9"
services:
  app:
    container_name: app
    restart: always
    image: app:latest
    build: .
    ports:
      - "8000:8000"
    command: sh -c "python manage.py makemigrations &&
      python manage.py migrate &&
      gunicorn core.wsgi:application --bind 0.0.0.0:8000"