name: Code Check CI/CD
on:
  workflow_dispatch:
jobs:
  deploy:
    name: check code
    runs-on: ubuntu-latest
    timeout-minutes: 10
    defaults:
      run:
        working-directory: ${{ github.workspace }}
    steps:
      - name: Check out the repo
        uses: actions/checkout@v3

      - name: Run app
        run: docker compose up -d --build

      - name: Curl
        run: |
          sleep 5s
          curl -v http://127.0.0.1:8000/course/list/

      - name: Run API Tests
        uses: actions/setup-node@v4
        with:
          node-version: '18'
      - run: npm install -g newman
      - run: newman run "${{ secrets.CHECK_FILE }}" --reporter-json-export ./newman/api-checker-report.json --verbose -r cli,json
        continue-on-error: true
      #      - run: newman run "https://api.getpostman.com/collections/${{collectionID}}?apikey=${{ secrets.POSTMANAPIKEY }}" --environment "https://api.getpostman.com/environments/${{ environmentID }}?apikey=${{ secrets.POSTMANAPIKEY }}"

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: api-checker-artifact
          path: ./newman/api-checker-report.json

#      - name: Set env as secret
#        env:
#          MY_VAL: ${{ secrets.PROJECT_ID }}
#        run: |
#          import os
#          for q in (os.getenv("MY_VAL")):
#            print(q)
#        shell: python

#      - name: Sleep
#        run: |
#          sleep 120s

      - name: Send run_id
        run: |
          curl --location 'https://api-dev.mohirpool.uz/api/site/accelerators/code-reviews/github-feedbacks/${{ github.actor }}/' \
          --header 'X-API-KEY: ${{ secrets.X_API_KEY }}' \
          --form 'action_run_id=${{ github.run_id }}' \
          --form 'project=${{ secrets.PROJECT_ID }}'
