name: Code Check CI/CD
on:
  push:
    branches: [ test ]

jobs:
  deploy:
    name: check code
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ${{ github.workspace }}
    steps:
      - name: Check out the repo
        uses: actions/checkout@v3

      - name: Install virtualenv
        run: python -m venv venv

      - name: Install requirements
        run: pip install -r requirements.txt

      - name: Run project
        run: gunicorn -b 0.0.0.0:8000 --workers=49 --threads=2 core.wsgi --reload --daemon

      - name: Curl
        run: curl -v http://127.0.0.1:8000/course/list/