name: Code Check CI/CD
on:
  push:
    branches: [ test ]

jobs:
  deploy:
    name: check code
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ${{ github.workspace }}
    steps:
      - name: Check out the repo
        uses: actions/checkout@v3

      - name: Run project
        run: python manage.py runserver