name: Code Check CI/CD
on:
  workflow_dispatch:
  push:
    branches: [ test ]
jobs:
  deploy:
    name: check code
    runs-on: ubuntu-latest
    timeout-minutes: 10
    defaults:
      run:
        working-directory: ${{ github.workspace }}
    steps:
      - name: Check out the repo
        uses: actions/checkout@v3

      - name: Run app
        run: docker compose up -d --build

      - name: Curl
        run: |
          sleep 5s
          curl -v http://127.0.0.1:8000/course/list/

      - name: Run API Tests
        uses: actions/setup-node@v4
        with:
          node-version: '18'
      - run: npm install -g newman
      - run: newman run https://api.postman.com/collections/16701660-18c0f4fe-5017-4290-a479-0aa7cac0d623?access_key=PMAT-01HFEM3C8MJKZ1W5YBDS3JYA4W --reporter-json-export ./newman/my_report.json --verbose -r cli,json
        continue-on-error: true
      #      - run: newman run "https://api.getpostman.com/collections/${{collectionID}}?apikey=${{ secrets.POSTMANAPIKEY }}" --environment "https://api.getpostman.com/environments/${{ environmentID }}?apikey=${{ secrets.POSTMANAPIKEY }}"

      - uses: actions/upload-artifact@v3
        with:
          name: my-artifact
          path: ./newman/my_report.json

      - name: Send run_id
        run: |
          curl --location 'https://api.mohirpool.uz/api/accelerator/github/actions-run-create/${{ github.actor }}/' \
          --header 'X-API-KEY: ${{ secrets.X_API_KEY }}' \
          --form 'actions_run_id=${{ github.run_id }}' \
          --form 'project=${{ secrets.PROJECT_ID }}'